name: Publish update

on:
  push:

jobs:
  update:
    name: Update
    type: update
    if: ${{ contains(github.event.head_commit.message, '[ci build]') }}
    params:
      branch: ${{ github.ref_name || ''}}
